version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: grao_transparente_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Monta o arquivo schema.sql para rodar automaticamente na criação do banco
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
